version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app_network
    environment:
      DOCKER_ENV: "1"

  mongo:
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge